# Generated by Django 5.2.12 on 2026-03-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='problems',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, max_length=10),
        ),
    ]
