# Generated by Django 5.2.12 on 2026-04-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problems_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problems',
            options={'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
    ]
