# Generated by Django 5.2.12 on 2026-03-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submissions_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='verdict',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
